### ISSUE TITLE
navbar responsive

### ISSUE THREAD

**Issue by ThiagoMowszet** [gophers-latam/gophers-latam.github.io#22]
El navbar debe de ser responsive para su uso en diferentes dispositivos:

![image](https://github.com/gophers-latam/gophers-latam.github.io/assets/73196303/e90e5a53-87c9-4157-ab0c-70d95dc269c3)

**Comment by zeroidentidad** [comment]
https://discord.com/channels/764989185077542942/1123784168925577266/1229966920917319690

**Comment by ThiagoMowszet** [comment]
se cierra el incidente, con la PR #35 de @miquigz
